inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Max: 135

Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FormatStringToken:
  EnforcedStyle: template
Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only
Style/NumericLiterals:
  Enabled: false
Style/NumericPredicate:
  EnforcedStyle: comparison
Style/SymbolArray:
  EnforcedStyle: brackets
