name: CI

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.6
          - 2.7
          - '3.0'
          - 3.1
          - ruby-head
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
      - name: Upload coverage report
        uses: codecov/codecov-action@v3

  system_test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.6
          - 2.7
          - '3.0'
          - 3.1
          - ruby-head
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run system test
        run: bundle exec rake system_test
      - name: Upload coverage report # It will be merged into the coverage for unit test
        uses: codecov/codecov-action@v3

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop
